version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201711-01
    environment:
      GOPATH: /home/circleci/go
      MINIKUBE_HOME: /home/circleci/go/src/github.com/utopia-planitia/docker-image-builder-service
    working_directory: ~/go/src/github.com/utopia-planitia/docker-image-builder-service
    steps:
      - restore_cache:
          name: restore tools cache
          keys:
            - tools-v2
      - checkout
      - run:
          name: install kubectl & minikube
          command: |
            if [ ! -f kubectl ]; then
              curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.4/bin/linux/amd64/kubectl
            fi
            chmod +x kubectl
            sudo cp kubectl /usr/local/bin/
            if [ ! -f minikube ]; then
              curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/v0.25.0/minikube-linux-amd64
            fi
            chmod +x minikube
            sudo cp minikube /usr/local/bin/
      - run:
          name: init minikube
          command: |
            make init
            sleep 65536
          background: true
      - run:
          name: install go metalinter
          command: |
            if [ ! -d gometalinter ]; then
              mkdir gometalinter
              go get -u github.com/alecthomas/gometalinter
              $GOPATH/bin/gometalinter --install
              mv $GOPATH/bin/* gometalinter
            fi
            sudo cp gometalinter/* /usr/local/bin/
      - run:
          name: preload docker imags
          command: |
            mkdir -p docker-image-cache
            cd docker-image-cache
            ../etc/docker-image.sh minio/minio:RELEASE.2018-02-09T22-40-05Z minio-RELEASE.2018-02-09T22-40-05Z
            ../etc/docker-image.sh docker:17.11.0-ce-dind                   docker-17.11.0-ce-dind
            ../etc/docker-image.sh golang:1.9.3-alpine3.7                   golang-1.9.3-alpine3.7
            ../etc/docker-image.sh alpine:3.7                               alpine-3.7
      - run:
          name: wait for minikube
          command: |
            make await
      - save_cache:
          name: save tools cache
          key: tools-v2
          paths:
            - kubectl
            - minikube
            - .minikube
            - docker-image-cache
            - .git
            - gometalinter
      - run:
          name: deploy
          command: |
            make deploy
      - run:
          name: tests
          command: |
            docker pull alpine:3.7
            docker save alpine:3.7 -o alpine37.tar
            make tests
      - run:
          name: lint bash
          command: |
            sudo apt-get update
            sudo apt-get install shellcheck
            shellcheck etc/*.sh caching-scripts/*.sh
      - run:
          name: lint go
          command: |
            go get -t ./...
            gometalinter ./...
