apiVersion: v1
kind: Service
metadata:
  name: builder
  namespace: container-image-builder
spec:
  clusterIP: None
  ports:
    - port: 2375
  selector:
    app: builder
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: builder
  namespace: container-image-builder
spec:
  replicas: 2
  serviceName: builder
  selector:
    matchLabels:
      app: builder
  template:
    metadata:
      labels:
        app: builder
    spec:
      containers:
        - name: builder
          image: utopiaplanitia/docker-image-builder-worker:latest
          imagePullPolicy: Never
          args:
            - builder
            - --docker=http://127.0.0.1:2376
          env:
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2375
            - name: CACHE_ENDPOINT_SERVER
              value: minio
            - name: CACHE_ENDPOINT_PORT
              value: "9000"
            - name: CACHE_BUCKET
              value: image-layers
            - name: CACHE_ACCESS_KEY
              value: 8Q9U4RBHKKB6HU70SRZ1
            - name: CACHE_SECRET_KEY
              value: oxxT2iqBlW6lgaDVe8ll6mP8z/OSVIUnn9cB4+Q0
          ports:
            - containerPort: 2375
              name: docker
          livenessProbe:
            tcpSocket:
              port: 2375
          readinessProbe:
            httpGet:
              path: /_ping
              port: 2375
        - name: docker
          image: docker:17.11.0-ce-dind
          args:
            - dockerd
            - --host=tcp://0.0.0.0:2376
            - --insecure-registry=10.0.0.0/8
            - --insecure-registry=172.16.0.0/12
            - --insecure-registry=192.168.0.0/16
          env:
            - name: DOCKER_DRIVER
              value: overlay2
          securityContext:
            privileged: true
          livenessProbe:
            tcpSocket:
              port: 2376