apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devtools
  namespace: container-image-builder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devtools
    spec:
      containers:
        - name: devtools
          image: utopiaplanitia/docker-image-builder-devtools:latest
          imagePullPolicy: Never
          args:
            - sh
            - -c
            - "sleep 4294967296"
          env:
            - name: DOCKER_HOST
              value: tcp://docker:2375